### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by mileyvirus** [buckket/ofgrab#3]
I'm using [the PR](https://github.com/buckket/ofgrab/pull/2) cause It features the updated classes but the issue persists, you're not getting auth, I thought the `sess` cookie was enough but didn't still work.

When I print the `post`'s HTML I see proof that I'm not authorized (even if I am subscribed to the profile). This is what I get when I print the `post`:
```HTML
    <div class="b-profile__restricted">
        <div class="b-profile__restricted__icon">
            <svg aria-hidden="true" class="g-icon">
                <use xlink:href="#icon-locked"></use>
            </svg>
        </div>
        <p>Please <a class="g-btn m-flat" data-toggle="modal" href="#subscribeModal"> <svg aria-hidden="true" class="g-icon">
                    <use xlink:href="#icon-follow"></use>
                </svg> Follow </a> <br /> to see this user's posts</p>
        <span class="b-profile__restricted__link"> <a class="g-btn m-flat" data-toggle="modal" href="#subscribeModal">
                <svg aria-hidden="true" class="g-icon">
                    <use xlink:href="#icon-follow"></use>
                </svg>
                Follow </a>
        </span>
    </div>
```

I tried going in incognito mode and creating a sess cookie and I don't know how in the world I get authed but it doesn't work in the script. 🤔

**Comment by buckket** [comment]
Authentication is fixed, see https://github.com/buckket/ofgrab/issues/1#issuecomment-486454316
