### ISSUE TITLE
Error while processing post

### ISSUE THREAD

**Issue by antiops** [buckket/ofgrab#5]
I keep getting an error when running this. I've followed the instructions, given it the right params but get this
```
[!] Found 10 posts on the start page
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Error while processing post x
[!] Fetching additional page
[!] Found 10 more posts
```

and it continues until it gets to the end `[!] Nothing more to process`

Tried on both windows 10 and ubuntu server with same results

**Comment by buckket** [comment]
Just tried to fetch a profile and everything seems still to be working for me.

Make sure you’re using the right value for the sess cookie. The User-Agent string has to be the exact same one your browser sent when logging in to OF.

What type of posts does the profile have you want to download? Currently the script only works with images and videos.

**Comment by antiops** [comment]
I got it working. I think the issue was me changing my user-agent and not logging back in to the account after refreshing. Did as you described and it works perfectly, thanks :D
