### ISSUE TITLE
grab_additional_page() not working anymore

### ISSUE THREAD

**Issue by ItsN3rdy** [buckket/ofgrab#6]
I'm trying to run the command in command prompt as:
`ofgrab.py itsn3rdy qwerty123abc Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36`

But I get:
[!] Found 10 posts on the start page
[!] Error while processing post 1
[!] Error while processing post 2
[!] Error while processing post 3
[!] Error while processing post 4
[!] Error while processing post 5
[!] Error while processing post 6
[!] Error while processing post 7
[!] Error while processing post 8
[!] Error while processing post 9
[!] Error while processing post 10
[!] Nothing more to process

any help??

**Comment by buckket** [comment]
Try (notice the quotes):
```sh
ofgrab.py itsn3rdy qwerty123abc "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
```

**Comment by ItsN3rdy** [comment]
that worked thanks

**Comment by ItsN3rdy** [comment]
Slightly different problem. Back when I was using the wrong code, It used to successfully get additional pages however it is now outputting "[!] Nothing more to process". I have ran it on multiple profiles but its not grabbing additional pages anymore.

**Comment by meptike** [comment]
Same for me, its only processing the first 10 posts.

**Comment by buckket** [comment]
I don’t have access to a profile with more than 10 posts and OF doesn’t let me create more than 3 posts or so on my test account before requesting ID. So I can’t debug this easily right now.

But as with the other Issues feel free to send me the HTML code of a profile via mail so I can take a look.

**Comment by meptike** [comment]
ok, what mail?

**Comment by mileyvirus** [comment]
> feel free to send me the HTML code of a profile

Hey @buckket, I sent you 4 HTML pages from the same profile via email:
```
1-profile-load-page-1-with-10-posts.html
2-scrolled-past-page-1-20-posts-now.html
3-scrolled-past-page-2.html
4-scrolled-past-page-3.html
```

**Comment by SmokE-PGF** [comment]
Just patched the issue with not being able to download more than the first 10 items https://github.com/buckket/ofgrab/pull/7

**Comment by buckket** [comment]
Merged. Thank you all.
