### ISSUE TITLE
again showing same error

### ISSUE THREAD

**Issue by deepakdhayal** [buckket/ofgrab#9]
./ofgrab.py 'ksaldada' 'bul4anhtpkjkamiqbf2bqdcf9r' "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0
[!] No posts found, there seems to be a problem

is there any solution for this?
or can you suggest what i might be doing wrong??

**Comment by buckket** [comment]
OF changed their site again, hence current version of the grabber does not work. See #8
